package tn.esprit.userservice.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.PrePersist;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.ColumnTransformer;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import tn.esprit.userservice.entities.converter.InetAddressConverter;
import tn.esprit.userservice.entities.enums.AuditEventType;

import java.net.InetAddress;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Composite PK (id, created_at) is required because audit_logs is partitioned by created_at.
 * The id is auto-generated by the BIGSERIAL sequence; created_at must be set before insert.
 */
@Entity
@Table(name = "audit_logs")
@IdClass(AuditLogId.class)
@Getter
@Setter
@NoArgsConstructor
public class AuditLog {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "audit_logs_id_seq")
    @SequenceGenerator(name = "audit_logs_id_seq", sequenceName = "audit_logs_id_seq", allocationSize = 1)
    @Column(name = "id", nullable = false, updatable = false)
    private Long id;

    @Id
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /**
     * Soft reference to the user — stored as a plain UUID, no FK constraint.
     *
     * Audit logs are forensic records and must not be coupled to users via a
     * database FK because:
     * 1. Registration events are logged while the INSERT for the user is still
     *    in an uncommitted transaction — a FK check would see the user as absent.
     * 2. Audit entries must survive user deletion.
     * 3. Anonymous / pre-auth events have no user at all.
     *
     * Use {@code JOIN audit_logs ON audit_logs.user_id = users.id} in queries
     * when you need user details alongside log entries.
     */
    @Column(name = "user_id")
    private UUID userId;

    @Enumerated(EnumType.STRING)
    @Column(name = "event_type", nullable = false, length = 40)
    private AuditEventType eventType;

    @Convert(converter = InetAddressConverter.class)
    @ColumnTransformer(write = "?::inet")
    @Column(name = "ip_address", columnDefinition = "inet")
    private InetAddress ipAddress;

    @Column(name = "user_agent", length = 512)
    private String userAgent;

    /**
     * Stored as JSONB in Postgres. Mapped as a String for now;
     * switch to a JsonNode/Map type when the JSONB serializer is wired up.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "details", columnDefinition = "jsonb")
    private String details;

    @PrePersist
    void onCreate() {
        if (createdAt == null) {
            createdAt = OffsetDateTime.now();
        }
    }
}
